spring:
  datasource:
    url: jdbc:mysql://mysql:3306/booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: booking
    password: booking

  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

jwt:
  secret: "${JWT_SECRET:jsJRg6qLq1aBfRvnxTu25G9hnRFIpEzi9G++AdqSfug=}"
  expiration-minutes: 60
